# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Stem": "00_constructor.ipynb",
         "BasicBlock": "00_constructor.ipynb",
         "Body": "00_constructor.ipynb",
         "Head": "00_constructor.ipynb",
         "init_model": "00_constructor.ipynb",
         "Net": "00_constructor.ipynb",
         "ConvLayer": "01_layers.ipynb",
         "act_fn": "01_layers.ipynb",
         "Flatten": "01_layers.ipynb",
         "Noop": "01_layers.ipynb",
         "Bottleneck": "02_resnet.ipynb",
         "resnet18": "02_resnet.ipynb",
         "resnet34": "02_resnet.ipynb",
         "resnet50": "02_resnet.ipynb"}

modules = ["constructor.py",
           "layers.py",
           "resnet.py"]

doc_url = "https://ayasyrev.github.io/model_constructor/"

git_url = "https://github.com/ayasyrev/model_constructor/tree/master/"

def custom_doc_links(name): return None
