# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ConvLayer": "00_constructor.ipynb",
         "Flatten": "00_constructor.ipynb",
         "Noop": "00_constructor.ipynb",
         "Stem": "00_constructor.ipynb",
         "BasicBlock": "00_constructor.ipynb",
         "Body": "00_constructor.ipynb",
         "Head": "00_constructor.ipynb",
         "init_model": "00_constructor.ipynb",
         "Net": "00_constructor.ipynb",
         "resnet18": "01_resnet.ipynb",
         "resnet34": "01_resnet.ipynb"}

modules = ["constructor.py",
           "resnet.py"]

doc_url = "https://ayasyrev.github.io/model_constructor/"

git_url = "https://github.com/ayasyrev/model_constructor/tree/master/"

def custom_doc_links(name): return None
