# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Stem": "00_constructor.ipynb",
         "BasicLayer": "00_constructor.ipynb",
         "Body": "00_constructor.ipynb",
         "Head": "00_constructor.ipynb",
         "init_model": "00_constructor.ipynb",
         "Net": "04_Net.ipynb",
         "ConvLayer": "01_layers.ipynb",
         "act_fn": "80_test_net.ipynb",
         "Flatten": "80_test_net.ipynb",
         "noop": "80_test_net.ipynb",
         "Noop": "01_layers.ipynb",
         "DownsampleBlock": "01_layers.ipynb",
         "BasicBlock": "01_layers.ipynb",
         "Bottleneck": "01_layers.ipynb",
         "DownsampleLayer": "01_layers.ipynb",
         "XResBlock": "01_layers.ipynb",
         "conv1d": "01_layers.ipynb",
         "SimpleSelfAttention": "01_layers.ipynb",
         "ConvBlockBasic": "01_layers.ipynb",
         "ConvBlockBottle": "01_layers.ipynb",
         "ResBlock": "80_test_net.ipynb",
         "resnet18": "02_resnet.ipynb",
         "resnet34": "02_resnet.ipynb",
         "resnet50": "02_resnet.ipynb",
         "xresnet18": "03_xresnet.ipynb",
         "xresnet34": "03_xresnet.ipynb",
         "xresnet50": "04_Net.ipynb",
         "init_cnn": "80_test_net.ipynb",
         "me": "80_test_net.ipynb",
         "conv": "80_test_net.ipynb",
         "conv_layer": "80_test_net.ipynb",
         "XResNet": "80_test_net.ipynb",
         "xresnet": "80_test_net.ipynb",
         "xresnet18_deep": "80_test_net.ipynb",
         "xresnet34_deep": "80_test_net.ipynb",
         "xresnet50_deep": "80_test_net.ipynb"}

modules = ["constructor.py",
           "layers.py",
           "resnet.py",
           "xresnet.py",
           "net.py",
           "tst_net.py"]

doc_url = "https://ayasyrev.github.io/model_constructor/"

git_url = "https://github.com/ayasyrev/model_constructor/tree/master/"

def custom_doc_links(name): return None
