# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['Net']

# Cell
class Net(nn.Sequential):
    '''Constructor for model'''
    def __init__(self,
#                  stem=Stem3L, body=Body, head=Head,
        # layers=[2,2,2,2,2], num_blocks=2,
        last_block_head=False,
        c_in=3, body_in=64, body_out=512, expansion=1, num_classes=10,
        init_type='normal', corr_first=False, **kwargs):
        # c_in = 3
        # block_szs  = [64,128,128,256,256,512]
        super().__init__(OrderedDict([
#             ('stem', stem(c_in=c_in,stem_out=body_in, corr_first=corr_first)),
#             ('body', body(body_in, body_out, expansion, corr_first=corr_first, **kwargs)),
#             ('head', head(body_out*expansion, num_classes))
            ]))
#         init_cnn(self, init_type=init_type)