# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/07_MXResNet.ipynb (unless otherwise specified).

__all__ = ['mxresnet_parameters']

# Cell
import torch.nn as nn
import sys, torch
from functools import partial
from collections import OrderedDict
from .layers import *
from .net import Net

# Cell
mxresnet_parameters = {'stem_sizes': [3, 32, 64, 64], 'act_fn': Mish()}