# AUTOGENERATED! DO NOT EDIT! File to edit: 01_resnet.ipynb (unless otherwise specified).

__all__ = ['resnet18', 'resnet34']

# Cell
import torch.nn as nn
import torch
from collections import OrderedDict

# Cell
from .constructor import *

# Cell
def resnet18(**kwargs):
    """Constructs a ResNet-18 model. """
    return Net(block=BasicBlock, blocks=[2, 2, 2, 2], **kwargs)
def resnet34(**kwargs):
    """Constructs a ResNet-18 model. """
    return Net(block=BasicBlock, blocks=[3, 4, 6, 3], **kwargs)