# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/80_test_net.ipynb (unless otherwise specified).

__all__ = []

# Cell
import torch.nn as nn
import torch
from collections import OrderedDict
from .constructor import *
from .layers import *