# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06_YResnet.ipynb (unless otherwise specified).

__all__ = ['YResBlock', 'yresnet34', 'yresnet50']

# Cell
import torch.nn as nn
import sys, torch
from functools import partial
from collections import OrderedDict
from .layers import *
from .net import Net

# Cell
# YResBlock - former NewResBlock.
class YResBlock(nn.Module):
    '''YResBlock. Reduce by pool instead of stride 2'''
    def __init__(self, expansion, ni, nh, stride=1,
                 conv_layer=ConvLayer, act_fn=act_fn, zero_bn=True, bn_1st=True,
                 pool=nn.AvgPool2d(2, ceil_mode=True), sa=False,sym=False, groups=1):
        super().__init__()
        nf,ni = nh*expansion,ni*expansion
        self.reduce = noop if stride==1 else pool
        layers  = [(f"conv_0", conv_layer(ni, nh, 3, stride=1, act_fn=act_fn, bn_1st=bn_1st)), # stride 1 !!!
                   (f"conv_1", conv_layer(nh, nf, 3, zero_bn=zero_bn, act=False, bn_1st=bn_1st))
        ] if expansion == 1 else [
                   (f"conv_0",conv_layer(ni, nh, 1, act_fn=act_fn, bn_1st=bn_1st)),
                   (f"conv_1",conv_layer(nh, nh, 3, stride=1, act_fn=act_fn, bn_1st=bn_1st, groups=int(nh/groups))), # stride 1 !!!
                   (f"conv_2",conv_layer(nh, nf, 1, zero_bn=zero_bn, act=False, bn_1st=bn_1st))
        ]
        if sa: layers.append(('sa', SimpleSelfAttention(nf,ks=1,sym=sym)))
        self.convs = nn.Sequential(OrderedDict(layers))
        self.idconv = noop if ni==nf else conv_layer(ni, nf, 1, act=False)
        self.merge =act_fn

    def forward(self, x):
        o = self.reduce(x)
        return self.merge(self.convs(o) + self.idconv(o))

# Cell
yresnet34  = partial(Net, block=YResBlock, expansion=1, layers=[3, 4,  6, 3], name='yresnet34')
yresnet50  = partial(Net, block=YResBlock, expansion=4, layers=[3, 4,  6, 3], name='yresnet50')